<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Users extends \Entities\Users implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setEmpId($empId)
    {
        $this->__load();
        return parent::setEmpId($empId);
    }

    public function getEmpId()
    {
        $this->__load();
        return parent::getEmpId();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateUpdated($dateUpdated)
    {
        $this->__load();
        return parent::setDateUpdated($dateUpdated);
    }

    public function getDateUpdated()
    {
        $this->__load();
        return parent::getDateUpdated();
    }

    public function setIsAdmin($isAdmin)
    {
        $this->__load();
        return parent::setIsAdmin($isAdmin);
    }

    public function getIsAdmin()
    {
        $this->__load();
        return parent::getIsAdmin();
    }

    public function setIsActive($isActive)
    {
        $this->__load();
        return parent::setIsActive($isActive);
    }

    public function getIsActive()
    {
        $this->__load();
        return parent::getIsActive();
    }

    public function setPhoneNumber($phoneNumber)
    {
        $this->__load();
        return parent::setPhoneNumber($phoneNumber);
    }

    public function getPhoneNumber()
    {
        $this->__load();
        return parent::getPhoneNumber();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function getUserDetail()
    {
        $this->__load();
        return parent::getUserDetail();
    }

    public function setUserDetail($userdetail)
    {
        $this->__load();
        return parent::setUserDetail($userdetail);
    }

    public function getUserSkillDetail()
    {
        $this->__load();
        return parent::getUserSkillDetail();
    }

    public function setUserSkillDetail($userskilldetail)
    {
        $this->__load();
        return parent::setUserSkillDetail($userskilldetail);
    }

    public function getEmployeeActivity()
    {
        $this->__load();
        return parent::getEmployeeActivity();
    }

    public function setEmployeeActivity($employeeactivity)
    {
        $this->__load();
        return parent::setEmployeeActivity($employeeactivity);
    }

    public function getUserRole()
    {
        $this->__load();
        return parent::getUserRole();
    }

    public function setUserRole($userrole)
    {
        $this->__load();
        return parent::setUserRole($userrole);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'userId', 'firstname', 'lastname', 'email', 'password', 'empId', 'dateCreated', 'dateUpdated', 'isAdmin', 'isActive', 'phoneNumber', 'username', 'userdetail', 'userskilldetail', 'userrole', 'employeeactivity');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}