<div class="wrapfooter">
   <div class="main">
      <div class="footerTop">
        <p class="links"><a href="#">Term & condition</a>  | <a href="#">Privacy</a>  |  <a href="http://synergytechservices.com/about/about-synergy.html" target="_blank">About us</a></p>
        <p class="fright">&copy; Copyright <?=date('Y')?> Synergy Resource Management</p>
        <div class="clear"></div>
      </div>
      <address class="fleft">
      Address: 701, Acropolis, Military Road, Andheri(E), Mumbai<br />
      Phone: +91 (22) 40751901
      </address>
      <div class="fright" style="padding:15px 0 0 0;">Designed by :  Synergy Technology Services</div>
      <div class="clear"></div>
   </div>
 </div>