<h2>What do we do exactly?</h2>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>

<ul id="leftmenu">
	<li><a href="#" rel="load">Complete project outsorcing</a></li>
	<li><a href="#" rel="load">Documentation outsorcing</a></li>
	<li><a href="#" rel="load">Support outsorcing</a></li>
</ul>
	
<div id="notice">
	<p></p>
</div>		
