<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>	
		<script src="/scripts/jquery-1.6.2.min.js"></script>
		<script src="/scripts/jquery-ui-1.8.15.custom.min.js"></script>
		<script src="/scripts/jquery.json-2.2.min.js"></script>    
		<link type="text/css" rel="stylesheet" href="/styles/bootstrap.css" />
		<link type="text/css" rel="stylesheet" href="/styles/reset.css" />
		<link type="text/css" rel="stylesheet" href="/styles/modalwindow.css" />
	</head>
	<body>
       <div class="mainwrapper">
			<div class="wrapcontainer">
				<div class="main" id="ajaxContent">
					<div class="content modalwindow">
						<?=$this->layout()->content; ?>
					</div>
				</div>
 			</div> 
			<div class="clear"></div>
		</div>
	</body>
	<body>
</html>