ALTER TABLE `resource_management`.`projects` ADD UNIQUE `Index_2`(`project_name`);

INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Berwicks Meter Portal And Data Synchronize Tool");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "BMSGroup Meter Portal And Data Synchronize Tool");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "CountOnMe Meter Portal And Data Synchronize Tool");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Challenge Disability Services Web Forms");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Cornish Web Forms");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Inland Technology Web Forms");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "eKaagazForFolders Connector For Copier");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "eKaagazForPVE Connector For Copier");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "ODBCToPaperVision");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Tamex");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Joomla Service provider");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "jSecure Authentication");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "JSP Location");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "wSecure Authentication");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "UNQ");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Neopacks");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Kambardarbar");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Creedenz");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "WAKM");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Bioquel");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "AMMAP Project");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Benee Jewelry");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Conti.ca");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Paralympic.ca");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Guadalajara 2011");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Paralympic Widgets");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "DosArrest");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Earls");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Eco Fashion World");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Firebox Training");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "FM Construction");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Food Service World");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Full Melt Glass");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Green Bull Products");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Guillevinsafety.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "HillFoods.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "HotelierMagazine.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "iseewest");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Kostuch Publications Website");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "hoteliermagazine.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "foodserviceworld.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "luxusaccessories.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Money Talks");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Moneytalks Events");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "My Green Hosting");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Novex");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Online culinary school");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Axis");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "PinnacleDrillingProducts.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "PsychicExpo");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "SaferHomeSociety");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Sanctuary For Kids");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "SoundHealthProducts.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Swingle and Associates");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Brownlee  Law ");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "McQuarrie Hunter LLP");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Watson Goepel Maledy LLP wgmlaw.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Swingle and Associates");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "The Cross Design");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "White Coat Resources");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Gheimtipp.ch");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Maharashtra State Security Corporation");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Synergy HR");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "cupe403.ca");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "kecke.ch");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "veonfirm.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "vasensavancouver.ca");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "unica.ch");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "rockbaaz.com");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Richmond Lawyers");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "patentochsner.ch");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Gordon Handford");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Futuretek projects");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Donmar");
INSERT INTO `resource_management`.`projects` (`project_id` ,`project_name`) VALUES (NULL , "Act community");