
<!-- <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img src="images/slider/img1.jpg" data-thumb="images/slider/img1.jpg" alt="" title="#htmlcaption" />
                <a href="http://dev7studios.com"><img src="images/slider/img2.jpg" data-thumb="images/slider/img2.jpg" alt="" title="#htmlcaption" /></a>
                <img src="images/slider/img3.jpg" data-thumb="images/slider/img3.jpg" alt="" title="#htmlcaption" />
                <img src="images/slider/img4.jpg" data-thumb="images/slider/img4.jpg" alt="" title="#htmlcaption" />
            </div>
            <div id="htmlcaption" class="nivo-html-caption">
               <a href="#" class="readmore">Tell me more</a>. 
            </div>
       </div>
        -->
	<h1 class="headbrd">Resource Management Application</h1>
	<p>In organizational studies, resource management is the efficient and
		effective deployment of an organization's resources when they are
		needed. Such resources may include financial resources, inventory,
		human skills, production resources, or information technology (IT). In
		the realm of project management, processes, techniques and
		philosophies as to the best approach for allocating resources have
		been developed.</p>
	<p>These include discussions on functional vs. cross-functional
		resource allocation as well as processes espoused by organizations
		like the Project Management Institute (PMI) through their Project
		Management Body of Knowledge (PMBOK) methodology of project
		management. Resource management is a key element to activity resource
		estimating and project human resource management. Both are essential
		components of a comprehensive project management plan to execute and
		monitor a project successfully.[1][2] As is the case with the larger
		discipline of project management, there are resource management
		software tools available that automate and assist the process of
		resource allocation to projects and portfolio resource transparency
		including supply and demand of resources.</p>