<script type="text/javascript">
function validateteamLeadForm(form){
	var validatePass = true;
	if($.trim($("#"+form+" #TeamLeadName").val())=='' || $("#"+form+" #TeamLeadName").val()==null){
		$("#TeamLeadName").focus();
		validatePass = false;
	}
	if(!validatePass)
	{
		$("#msg").html("Please Select atleast one Team Lead");
		return false;
	}
}
$(document).ready(function() {
	$('select').each(function(){
		var id=$(this).attr('id');
		$("#"+id).select2();
	});
});
</script>
<h1 class="headbrd">Add Team Lead</h1>
<p id="msg" style="color:#A52A2A;"></p>

<form class="teamLeadForm" id="teamLeadForm" action="/admin/addteamlead" method="post" onsubmit="return validateteamLeadForm('teamLeadForm')">
	 <?php  if(!empty($this->users)){?>
	 <div class="profileheadbox role">
		<p class="firstName formfield">
			<label for="TeamLead" class="span4"> Select Team Lead  </label>
				<select  multiple class="span4" name="TeamLead[]" id="TeamLeadName">
				<?php foreach($this->users as $user){
				 echo "<option value=".$user->getUser()->getUserId().">".$user->getUser()->getFirstName()." ".$user->getUser()->getLastName()."</option>";

				}?>
				</select>
		</p>
        <div class="clear"></div>
	</div>
	<table class="profileDetails table table table-striped table-bordered" cellpadding="0" cellspacing="1" width="100%">
	<tbody>
			<tr class="profilefooterbox" style="float:none;">
				<td class="text-right" colspan="3" style="padding:8px 10px">
	        		<input type="submit" name="Submit" value="Add" class="btn btn-primary btn-small">
                    <a class="btn btn-small" href="/admin/manageteam">Cancel</a>
				</td>
        	</tr>
        	<?php } else {?>
        	<tr class="profilefooterbox" style="float:none;">
				<td class="text-right" colspan="3" style="padding:8px 10px">
	        		<div>No Employees are Remaining to Assign</div><br>
                    <a class="btn btn-small" href="/admin/manageteam">Back</a>
				</td>
        	</tr>
        	<?php } ?>
	</tbody>
</table>