<script type="text/javascript">
function validateRoleForm(form){
	var validatePass = true;
	if($.trim($("#"+form+" #roleName").val())=='' || $("#"+form+" #roleName").val()==null){
		$("#invalid_roleName").html('Role name can not be empty');
		$("#roleName").focus();
		validatePass = false;
	}

	if($('.check:checked').size()==0){
		$("#msg").html("Please select at least one checkbox");
		validatePass = false;
	}
	if(!validatePass)
		return false;
}

$("#selectAll").live('click',function () {
	$("#msg").html("");
    $('.check').attr('checked', this.checked);
    if($(this).parent().hasClass('checked'))
		$(this).parent().removeClass('checked');
	else{
		$(this).parent().addClass('checked');
	}

    if($(this).parent().hasClass('checked'))
		$('.check').parent().addClass('checked');
	else
		$('.check').parent().removeClass('checked');
});

$(".check").live('click',function(){
	$("#msg").html("");
	 if($(".check").length == $(".check:checked").length) {
	        $("#selectAll").attr("checked", "checked");
	        $("#selectAll").parent().addClass('checked');
	    } else {
	        $("#selectAll").removeAttr("checked");
	        $("#selectAll").parent().removeClass('checked');
	    }
	if($(this).parent().hasClass('checked')){
		$(this).parent().removeClass('checked');
		$(this).removeAttr("checked");
	}
	else{
		$(this).attr("checked", "checked");
		$(this).parent().addClass('checked');
	}
});
keyUpTime = 500; // 1 sec
keyUpTimeout = null;
$('#roleName').live('keyup',function(){
	var roleName = $(this).val();
	$('#invalid_roleName').html('');
	clearTimeout(keyUpTimeout);
	var item = {
			roleName : roleName,
			roleId : <?=$this->role->getRoleId();?>
	};
	keyUpTimeout = setTimeout(function() {$.ajax({
 		type : 'POST',
 		url: '/admin/validaterolename/',
    	data: "format=json&data="+$.toJSON(item),
    	success: function(res, stat) {
    		if(!res){
    			$('#invalid_roleName').addClass('displayblock');
    			$('#invalid_roleName').html('Role already exists');
    		}
    	}
		});
	},keyUpTime);
});
</script>
<div class="headTitle">
	    <h1 class="headbrd">Edit Permissions for "<?=$this->role->getRoleName();?>"</h1>
	    <p id="msg" style="color:#A52A2A;"></p>
	</div>
    <form name="rolePermission" id="roleForm" action="/admin/editrolepermission/roleId/<?=$this->role->getRoleId();?>" method="post" onsubmit="return validateRoleForm('roleForm')">
    <div class="profileheadbox role">
		<p class="firstName formfield">
			<label for="name" class="span2">Role Name</label>
			<span class="span3">
				<input type="text" name="roleName" id="roleName" value="<?=$this->role->getRoleName();?>">
				<span id="invalid_roleName" class="error_text displayblock"></span>
		    </span>
		</p>
        <div class="clear"></div>
        <h1 style="margin:0; padding:0 18px;">Permissions</h1>
	</div>
<table class="profileDetails table table table-striped table-bordered" cellpadding="0" cellspacing="1" width="100%">
	<thead>
		<tr>
			<td width="5%" style="text-align:center;">
				<div class="">
                         <span class="">
                               <input type="checkbox" name="check[]"  id="selectAll">
                          </span>
                </div>
			</td>
			<td class=" profileaside txtleft" width="25%"><label>Privilage</label></td>
			<td class=" profileaside txtleft" width="70%"><label>Description</label></td>
		</tr>
	</thead>
	<tbody>
			<?php $count = 1;
			foreach ($this->permissions as $resource => $permission){
			?>
				<tr>
					<td class="span2 profileaside" colspan="3" style="text-align:center; padding:6px 0; font-size:14px">
						<b>Resource : <?=ucfirst($resource);?></b>
                     </td>
                 </tr>
						<?php foreach ($permission as $permissionId => $privilage){?>
						<tr>
							<td width="5%" style="text-align:center;">
                              <div class="">
                              <span class="<?php echo in_array($permissionId, $this->selectedPermissionIdArr) ? 'checked' : ''?>">
								<input type="checkbox" class="check" name="permission[]" value="<?=$permissionId?>" <?php echo in_array($permissionId, $this->selectedPermissionIdArr) ? 'checked="checked"' : ''?>>
                                </span>
                                </div>
							</td>
							<td width="25%">
							<?=$privilage['privilage'];?>
							</td>
							<td width="70%">
							<?=$privilage['description']?>
							</td>
						</tr>
						<?php }?>
			<?php }?>
			<tr class="profilefooterbox" style="float:none;">
				<td class="text-right" colspan="3" style="padding:8px 10px">
	        		<input type="submit" name="Submit" value="Submit" class="btn btn-primary btn-small">
                    <a class="btn btn-small" href="/admin/managerolepermission">Cancel</a>
				</td>
        	</tr>
	</tbody>
</table>
</form>