<script type="text/javascript" src="/scripts/google_jsapi.js"></script>
<?php
$userSkillDetail = $this->user->getUserSkillDetail();
$photoUrl = '/images/userLogin2.png';
?>
<script type="text/javascript">
google.load('visualization', '1', {packages: ['corechart','table']});
function init() {
    var options = {
	'legend': 'bottom',
      animation:{
    	width: 600,
        height: 240,
        duration: 1000,
        easing: 'out',
      },
      vAxis: {title: "Experience in months (50 = More than 48 Months of exp)", minValue:0, maxValue:50},
      hAxis: {viewWindow: {min:0, max:<?= count($userSkillDetail)>0 ? count($userSkillDetail) : 10?>}}
    };
    var skillCount = 0;
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Experience in months');
    data.addColumn('number', 'Skills(Experience in months)');
    var chart = new google.visualization.ColumnChart(document.getElementById('visualization'));
    var prevButton = document.getElementById('prevBtn');
    var nextButton = document.getElementById('nxtBtn');
    var changeZoomButton = document.getElementById('zoomBtn');
    function drawChart() {
        // Disabling the button while the chart is drawing.
        
        prevButton.disabled = true;
        nextButton.disabled = true;
        changeZoomButton.disabled = true;
        chart.draw(data, options);
      }
      prevButton.onclick = function() {
          options.hAxis.viewWindow.min -= 10;
          options.hAxis.viewWindow.max -= 10;
          drawChart();
        }
      nextButton.onclick = function() {
          options.hAxis.viewWindow.min += 10;
          options.hAxis.viewWindow.max += 10;
          drawChart();
      }
      var zoomed = false;
      changeZoomButton.onclick = function() {
          if (zoomed) {
            options.hAxis.viewWindow.min = 0;
            options.hAxis.viewWindow.max = 10;
            $("#zoomBtn i").removeClass("icon-zoom-out");
          } else {
            options.hAxis.viewWindow.min = 0;
            options.hAxis.viewWindow.max = <?=count($userSkillDetail)?>;
            $("#zoomBtn i").addClass("icon-zoom-out");
          }
          zoomed = !zoomed;
          drawChart();
        }
      
    <?php if(count($userSkillDetail)>0){
			foreach($userSkillDetail as $userSkill){?>
    			data.addRow(['<?=$userSkill->getSkill()->getSkillName().'-'.$userSkill->getLevel()->getLevelName();?>', <?=$userSkill->getExpMonths()=='48 + ' ? 50 : $userSkill->getExpMonths();?>]);
    			skillCount = skillCount+1;
    <?php }?>
    options.hAxis.viewWindow.min = 0;
    options.hAxis.viewWindow.max = 10;
	<?php }else{?>
	 data.addRow(['', 0]);
	<?php }?>
	google.visualization.events.addListener(chart, 'ready',
            function() {
              prevButton.disabled = options.hAxis.viewWindow.min <= 0;
              nextButton.disabled = options.hAxis.viewWindow.max >= skillCount;
              if(skillCount>5)
              	changeZoomButton.disabled = false;
    });
	if(skillCount<=10){
	    prevButton.disabled = true;
	    nextButton.disabled = true;
	    changeZoomButton.disabled = true;
	}
	  chart.draw(data, options);
}
google.setOnLoadCallback(init);
</script>
	<div class="headTitle">
	    <h1 class="headbrd">Your Profile Graph</h1>
	</div>
	<div class="profilehead">
		<div class="profileimg col_6 fleft" style="padding-left:10px;">
			<p>
				<img src="<?=$photoUrl?>" width="60" height="60" alt=" " />
				<?=$this->user->getFirstName()." ".$this->user->getLastName();?>
			</p>
		</div>
		<!-- <div class="fleft info col_4">
		<p><span>Date of Birth</span> : 12 june 1988</p>
		<p><span>Gender</span> : male</p>
		<p><span>language</span> : English, Hindi, German</p>
		</div> -->
	</div>
    <div class="clear"></div>
		<div class="row-fluid show-grid panel">
		    <span class="span12">
		      	<div class="row-fluid">
			        <div class="" >
			              <div class="span12">
			                
			               <div class="btn-toolbar chartAction">
			                   <div class="actions">
			                      <button type="button" id="nxtBtn" class="btn"><i class="icon-chevron-right"></i></button>
			                      <button type="button" id="prevBtn" class="btn"><i class="icon-chevron-left"></i></button>
			                      <button type="button" id="zoomBtn" class="btn"><i class="icon-zoom-in"></i></button>
			                   </div>
			              </div>
			              <div class="visualPanel">
			              <?php if(count($userSkillDetail)==0){?>
                          <div class="noData">
                           <div class="over"></div>
                            <div class="detail">
                            <p align="center">No Skills added yet. Why not to add one?</p>
							<p align="center"><a href="/user/updateskill/userId/<?=$this->user->getUserId()?>">Manage Your Skills<span class="displayblock"><img src="/images/manage-plus.png"/></span></a></p>
                            </div>
                          </div>
                          <?php }?>
                          <div id="visualization" class="wrap-bordered" style="width:100%; height: 400px;"></div>
                          </div>
			           </div>
			        </div>
		    	</div>
			</span>
		</div>