<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" class="prev">
    Previous
  </a>
<?php else: ?>
  <span class="disabled prev">Previous</span>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>" class="number">
        <?php echo $page; ?>
    </a>
  <?php else: ?>
    <span class="number"><?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>" class="nxt">
    Next
  </a>
<?php else: ?>
  <span class="disabled nxt">Next</span>
<?php endif; ?>
</div>
<?php endif; ?>